name: Chebfun Tests on Octave

on: [push, pull_request, workflow_dispatch]

jobs:
  test-octave:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kolmanthomas/chebfun:octave-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Chebfun tests
        run: octave --eval "addpath(genpath(pwd)); chebtest('ballfun', 'ballfunv', 'bndfun', 'classicfun', 'chebfun', 'chebfun2', 'chebfun3', 'chebgui', 'chebmatrix', 'chebpref', 'deltafun', 'diskfun', 'diskfunv', 'fun', 'functionalBlock', 'misc', 'operatorBlock', 'singfun', 'spherefun', 'spherefunv', 'spinop', 'spinop2', 'spinop3', 'spinopsphere', 'spinpref', 'spinpref2', 'spinpref3', 'spinprefsphere', 'spinscheme', 'treeVar', 'trigspec', 'trigtech', 'unbndfun', '--log')"

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: chebtest-log
          path: ./*.log
          retention-days: 30

